steps:
  # Step 1: Build the Docker image from the Dockerfile in the source repository.
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-east1-docker.pkg.dev/${PROJECT_ID}/Artificial-Cognitive-Entity/acee-api/acee-api', '.']

  # Step 2: Push the image to Google Artifact Registry.
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east1-docker.pkg.dev/${PROJECT_ID}/Artificial-Cognitive-Entity/acee-api/acee-api']

  # Step 3: Deploy the image to Cloud Run.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'acee-api' # The name of the Cloud Run service
    - '--image'
    - 'us-east1-docker.pkg.dev/${PROJECT_ID}/Artificial-Cognitive-Entity/acee-api/acee-api'
    - '--region'
    - 'us-east1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'

# images:
#   - 'gcr.io/$PROJECT_ID/cloud-run-source-deploy/acee-api/acee-api:$SHORT_SHA'

# timeout: '3600s' # 1 hour timeout, match this to your build's requirements

# substitutions:
#   _AR_HOSTNAME: 'us-east1-docker.pkg.dev'
#   _PLATFORM: 'managed'
#   _DEPLOY_REGION: 'us-east1'
#   _TRIGGER_ID: '0a28f2ea-6f92-4e31-a742-14f7793989b8'
#   _SERVICE_NAME: 'acee-api'
