import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/navigation/navbar/navbar'
import ModeSwap from './components/ModeSwap'

const inter = Inter({ subsets: ['latin'] })

//website meta data
export const metadata: Metadata = {
  title: 'ACEE Landing Page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <Navbar />{children}</body>

    </html>
  )
}

//children represents page where the user is at any given time